version: '3.8'

services:
  server-a:
    build:
      context: ./serverA
    container_name: server-a
    ports:
      - "3080:3080"

  server-b:
    build:
      context: ./serverB
    container_name: server-b
    ports:
      - "3081:3081"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "3000:3000"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/:/etc/nginx/ssl/
    depends_on:
      - server-a
      - server-b